# Generated by Django 6.0.4 on 2026-04-22 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_servico_agendamento_observacao_agendamento_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 22, 14, 37, 22, 746010)),
            preserve_default=False,
        ),
    ]
