# Generated by Django 6.0.4 on 2026-04-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agendamento_criado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='criado_em',
        ),
    ]
