# Generated by Django 6.0.4 on 2026-04-28 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendamento_status'),
        ('agenda', '0004_remove_agendamento_criado_em'),
    ]

    operations = [
    ]
